<a href="https://colab.research.google.com/github/duarteleonardosales/Analise-Descritiva/blob/main/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.preprocessing import normalize
import pandas as pd
import statsmodels.stats.outliers_influence

data = pd.read_csv('Dataset.csv', header='infer')

data[['ln(area)','bedroom','bathroom','garage']]

      ln(area)  bedroom  bathroom  garage
0     5.337538      3.0       4.0     2.0
1     4.290459      2.0       2.0     1.0
2     5.652489      3.0       4.0     3.0
3     4.382027      2.0       3.0     1.0
4     5.888878      4.0       6.0     3.0
...        ...      ...       ...     ...
2968  5.252273      3.0       3.0     2.0
2969  5.940171      4.0       5.0     2.0
2970  5.545177      3.0       1.0     3.0
2971  4.753590      4.0       5.0     2.0
2972  4.553877      3.0       2.0     2.0

[2973 rows x 4 columns]

In [ ]:
data = data.to_numpy()
data = normalize(data, axis=0, norm='l2')

data_transposta = data.transpose()
x_x = np.dot(data_transposta, data)
k_index = np.sqrt(np.linalg.eigvals(x_x).max() / np.linalg.eigvals(x_x).min())

print(k_index)

- VIF - AREA: 2.71
- VIF - QUARTO: 2.06
- VIF - WC: 2.1
- VIF - VAGAS: 1.76

In [ ]:
test_mult_vif = []
for i in range(4):
  test_mult_vif.append(statsmodels.stats.outliers_influence.variance_inflation_factor(data,i+1))
print(test_mult_vif)

[2.7144962516862106, 2.056658558420808, 2.099127038286176, 1.7575008825758571]